Foolerton/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foolertonApp.urls', namespace='foolertonApp')),
]

foolertonApp/urls.py
from django.urls import path, include

from . import views

app_name = 'foolerton'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('logout', views.logoutacc, name='logout'),
    path('createuser', views.createUser, name='createuser'),
    path('createtasks', views.createtasks, name='createtasks'),
    path('createtasks/<name>/<date>', views.createtasks, name='createtasks'),
    path('createdtasks', views.createdtasks, name='createdtasks'),
    path('updatetasks', views.updatetasks, name='updatetasks'),
    path('delete', views.deleteTask, name="deleteTask"),
    path('mark', views.MarkTask, name="MarkTask"),
    path('tasks/', views.view_tasks, name='tasks'),
    path('tasks', views.view_tasks, name='tasks'),
    path('completedtasks', views.mark_task_as_completed, name='completedtasks'),
    path('uploadMedical', views.upload_medical, name='upload_medical'),
    path('healthinfo', views.healthinfo, name='healthinfo'),
    path('healthinfo/<name>', views.healthinfo, name='healthinfo'),
    path('docacc', views.docacc, name='docacc'),
    path('manage', views.manage, name='manage'),
    path('update', views.update, name='update'),
    path('change', views.change, name='change'),
    path('createpat', views.createpat, name='createpat'),
    path('addcare/<pat>', views.addcare, name='addcare'),
    path('removecare/<pat>', views.removecare, name='removecare'),
    path('createcomments', views.createcomments, name='createcomments'),
    path('testHTTPEndPoint', views.testHTTPEndPoint, name='testHTTPEndPoint'),
    path('email', views.notification, name='notification'),
    path('test', views.taskcre, name='test'),
]

foolertonApp/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone, dateformat
# Create your models here.


CHAR_LENGTH = 255


class UserManager(BaseUserManager):
    def create_user(self, email, name, password=None, **extra_fields):
        """Create user by email, name, password"""
        if not email:
            raise ValueError('User must have an email!')
        user = self.model(email=self.normalize_email(
            email), name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, name, password):
        """Create superuser by email, name, password"""
        user = self.create_user(email=email, name=name, password=password)
        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.save(using=self.db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom User model"""
    USERNAME_FIELD = 'email'
    email = models.EmailField(max_length=CHAR_LENGTH, unique=True)
    name = models.CharField(max_length=CHAR_LENGTH)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    User_Type = (
        ('doctor', 'doctor'),
        ('careTaker', 'careTaker'),
    )
    user_type = models.CharField(max_length=40,
                                 choices=User_Type,
                                 default='careTaker'
                                 )
    created_at = models.DateTimeField(default=timezone.now)

    objects = UserManager()

    def __str__(self):
        return self.email

    def __repr__(self):
        return f"{self.email!r}, {self.is_staff!r}, {self.is_active!r}, "


class Patient(models.Model):
    NRIC = models.CharField(max_length=20)
    name = models.CharField(max_length=40)

    # doctor = models.ForeignKey(
    #     User, related_name="doc", on_delete=models.CASCADE)
    # careTaker = models.ForeignKey(
    #     User, related_name="care", on_delete=models.CASCADE, null=True, blank=True)


class DoctorToPatient(models.Model):
    Patient = models.ForeignKey(
        Patient, related_name="patient_doc", on_delete=models.CASCADE)
    Doctor = models.ForeignKey(
        User, related_name="doc", on_delete=models.CASCADE)


class CaretakerToPatient(models.Model):
    Patient = models.ForeignKey(
        Patient, related_name="patient_care", on_delete=models.CASCADE)
    Caretaker = models.ForeignKey(
        User, related_name="care", on_delete=models.CASCADE)


class MedicalDetails(models.Model):
    Patient = models.ForeignKey(
        Patient, related_name="patient_dets", on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now, null=True, blank=True)
    bloodPressure = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    heartRate = models.IntegerField(null=True, blank=True)
    MedicalCondition = models.CharField(max_length=200, default="")
    Medication = models.CharField(max_length=200, default="")
    allergies = models.CharField(max_length=200, default="")


class Task(models.Model):
    Patient = models.ForeignKey(
        Patient, related_name="patient_task", on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    # whether task 1 or 2 or 3 for that date, shld be auto filled when create task
    details = models.CharField(max_length=120, blank=True, null=True)
    editBy = models.CharField(max_length=60, blank=True, null=True)
    editDate = models.DateField(default=timezone.now)
    completedFlag = models.BooleanField(default=False)


class Comments(models.Model):
    task = models.ForeignKey(
        Task, related_name="comment_task", on_delete=models.CASCADE)
    comment = models.CharField(max_length=160, blank=True, null=True)
    editBy = models.CharField(max_length=60, blank=True, null=True)
    editDate = models.DateField(default=timezone.now)
    time = models.TimeField()

foolertonApp/views.py
from xml.etree.ElementTree import Comment
from django_celery_beat.models import PeriodicTask, PeriodicTasks, CrontabSchedule, ClockedSchedule
import datetime
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from urllib3 import HTTPResponse
import json
from .models import User, Task
from .models import *
from django.core.mail import send_mail
import random


# Create your views here.


def test(request):

    return render(request, 'base.html')


def createUser(request):

    if request.method == "GET":
        return render(request, 'register_page.html')

    if request.method == "POST":
        if(User.objects.filter(email=request.POST['email'])):
            return render(request, 'register_page.html', {'message': 'Email is already in use'})
        if request.POST['password'] != request.POST['repassword']:
            return render(request, 'register_page.html', {'message': 'Passwords do not match'})

        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        userType = 'careTaker'
        use = User.objects.create_user(
            email, name, password)
        use.user_type = userType
        use.save()
        # if(userType == 'careTaker'):
        #     nric = request.POST['nric']
        #     care = CaretakerToPatient.objects.create(
        #         Caretaker=use, Patient=Patient.objects.get(NRIC=nric))
        #     care.save()
        content = {'Success': "created for " + use.name}
        return render(request, 'register_page.html', content)


def createtasks(request, name, date):
    if request.method == "GET":
        user = request.user
        if(user.user_type == 'doctor'):
            patients = DoctorToPatient.objects.filter(Doctor=user)
            ppl = []
            for patient in patients:
                ppl.append(patient.Patient)
            tasklist = Task.objects.all().filter(
                Patient__pk=name, date=date).order_by('time')
            comment = []
            task_complete = []
            for i in tasklist:
                comments = i.comment_task.all()
                comment.append({"tasked": i, "comment": comments})
                task_complete.append(i.completedFlag)
            context = {
                'comments': comment,
                'dates': date,
                'people': ppl,
                'current': name,
                'name': request.user.name,
            }
            # For js convenience
            context["task_completedFlag"] = json.dumps(task_complete)
            return render(request, 'tasks_page_main.html', context)
        if(user.user_type == 'careTaker'):
            patients = CaretakerToPatient.objects.filter(Caretaker=user)
            ppl = []
            for patient in patients:
                ppl.append(patient.Patient)
            tasklist = Task.objects.all().filter(
                Patient__pk=name, date=date).order_by('time')
            comment = []
            task_complete = []
            for i in tasklist:
                comments = i.comment_task.all()
                comment.append({"tasked": i, "comment": comments})
                task_complete.append(i.completedFlag)
            context = {
                'comments': comment,
                'dates': date,
                'people': ppl,
                'current': name,
                'name': request.user.name
            }
            context["task_completedFlag"] = json.dumps(task_complete)
            return render(request, 'tasks_page_main_care.html', context)


def createdtasks(request):
    if request.method == "POST":
        if request.POST.get("form_type") == 'addtask':

            id = request.POST.get('person')
            Patiented = Patient.objects.filter(
                pk=id).first()  # testing
            date = request.POST.get('datecomplete')
            time = request.POST.get('timecomplete')
            details = request.POST.get('taskdesc')
            editBy = request.user.name

            newTask = Task(date=date, Patient=Patiented,
                           time=time, details=details, editBy=editBy)
            newTask.save()
            dat = datetime.datetime.combine(datetime.datetime.strptime(
                date, '%Y-%m-%d').date(), datetime.datetime.strptime(time, '%H:%M').time())
            dat = dat - datetime.timedelta(hours=1)
            schedule, created = ClockedSchedule.objects.get_or_create(
                clocked_time=dat)
            task = PeriodicTask.objects.create(
                clocked=schedule, name=str(datetime.datetime.now())+newTask.date+newTask.time+str(Patiented.pk), task='foolertonApp.tasks.autoemail', one_off=True)
            whr = '/createtasks/'+str(Patiented.pk)+'/'+date
            return redirect(whr)
    # just load this first if it doesnt work
    return render(request, 'loginpg.html')


def createcomments(request):
    if request.method == "POST":
        Tasked = Task.objects.filter(pk=request.POST.get('task')).first()
        comment = request.POST.get('comment_desc')
        date = request.POST.get('date')
        print(date, "adsdas")
        com = Comments.objects.create(
            task=Tasked, comment=comment, editBy=request.user.name, editDate=datetime.datetime.now(), time=datetime.datetime.now())
        com.save()
        name = request.POST.get('name')
        whr = '/createtasks/'+name+'/'+date
        return redirect(whr)


def updatetasks(request):
    if request.method == "POST":
        if request.POST.get("form_type") == 'updatetask':

            name = request.POST.get('name')
            Patiented = Patient.objects.filter(
                name=name).first()  # testing
            date = request.POST.get('datecomplete')
            time = request.POST.get('timecomplete')
            details = request.POST.get('taskdesc')
            editBy = request.user.name
            # Patient_id = 1
            newTask = Task.objects.filter(pk=request.POST.get('task')).first()
            newTask.date = date
            newTask.time = time
            newTask.details = details
            newTask.editBy = editBy
            newTask.save()
            whr = '/createtasks/'+name+'/'+date
            return redirect(whr)
    # just load this first if it doesnt work
    return render(request, 'loginpg.html')


def deleteTask(request):
    if request.method == "DELETE":
        data = json.loads(request.body.decode("utf-8"))
        id = int(data["task_id"])
        task = Task.objects.filter(id=id).first()
        if(task):
            task.delete()
            res = HttpResponse(f"Success, Task {id} is deleted")
            res.status_code = 200
            return res
        else:
            res = HttpResponse(f"Error Task {id} Not Found")
            res.status_code = 400
            return res


def MarkTask(request):
    if request.method == "POST":
        data = json.loads(request.body.decode("utf-8"))
        id = int(data["task_id"])
        task = Task.objects.filter(id=id).first()
        if(task):
            task.completedFlag = not task.completedFlag
            task.save()
            if task.completedFlag:
                res = HttpResponse(f"Success, Task {id} set as completed")
            else:
                res = HttpResponse(f"Success, Task {id} set as uncompleted")
            res.status_code = 200
            return res
        else:
            res = HttpResponse("Failure, cannot find task")
            res.status_code = 400
            return res


def login_user(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            if user.user_type == 'doctor':
                patients = DoctorToPatient.objects.filter(Doctor=user).first()

                if patients == None:
                    patients = "-1"
                else:
                    patients = patients.Patient.pk
                whr = '/createtasks/'+str(patients) + \
                    '/'+str(datetime.datetime.now().date())
                return redirect(whr)
            if user.user_type == 'careTaker':
                patients = CaretakerToPatient.objects.filter(
                    Caretaker=user).first()

                if patients == None:
                    patients = "-1"
                else:
                    patients = patients.Patient.pk
                whr = '/createtasks/'+str(patients)+'/' + \
                    str(datetime.datetime.now().date())
                return redirect(whr)
        else:
            message = "Unsuccessful login! Please enter the right email and password!"
            return render(request, 'login_page.html', {'message': message})
    if request.method == "GET":
        return render(request, 'login_page.html')


def view_tasks(request):
    if request.method == "GET":
        query_tasks = Task.objects.filter(
            Patient=request.GET['patient_id'],
            date=request.GET['date']
        ).order_by('number')
        if query_tasks is not None:
            tasks_comments_dict = {}
            for task in query_tasks:
                # cant seem to fetch comments due to conversion error?
                query_comment = Comments.objects.filter(task_id=task.id)
                if query_comment is not None:
                    comments_dict = {
                        comment.id: comment for comment in query_comment}
                    tasks_comments_dict[task.number] = (
                        task, comments_dict)
                else:
                    tasks_comments_dict[task.number] = (task, None)
            print(tasks_comments_dict)
            return render(request, 'testpage.html', {'task_query': tasks_comments_dict})

foolertonApp/templates/create_tasks_successful.html
<!--- JUST FOR TESTING-->
<!--- JUST FOR TESTING-->
<!--- JUST FOR TESTING-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form>
        {% csrf_token %}
        sup fam<br>
        Description {{taskdesc}}<br>
        Time of Completion {{timecomplete}}<br>
        Date of Completion {{datecomplete}}<br>
     </form>

</body>
</html>

foolertonApp/templates/login_page.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>Login Page</title>
        <link href="{% static 'css/signup.css'%}" rel="stylesheet" />
        
        <!--fonts-->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:600">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    </head>

    <body>
        <div class="wrapper">
            <div class="split_left" >
                <div class="split_left_content">
                    <p class="app_header">FOOLERTON</p>
                    <img src="{% static 'assets/logo.png'%}" width="560" height="380">                    
                </div>
            </div>
            <div class="split_right">
                <p class="signup_header">Login</p>
                <form class="loginForm" method="POST" action="{% url 'foolerton:login' %}" autocomplete="on">
                    {% csrf_token %}
                    <div class="email_field">
                        <label class="email_input_label_login" for="email"> <b>Email address:</b> </label>
                        <input type="text" name="email" id="email" required>                        
                    </div>

                    <div class="password_field"> 
                        <label class="password_input_label" for="password"> <b>Password:</b> </label>
                        <input type="password" name="password" id="password"required>                        
                    </div>

                    <button class="submit_button">Login</button>
                </form>

                <div class="login_no_account">
                    <a>Don’t have an account?</a>
                    <a href="{% url 'foolerton:createuser' %}"><button class="login_create_account" >Click here to create.</button></a>
                </div>

                <center>
                    <p class="signup_header">   
                        {{message}}
                    </p>
                </center>
            </div>
        </div>
    </body>
</html>

foolertonApp/templates/tasks_page_main.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
    <title>Task Page</title>
    <!-- <link href="{% static 'css/reusable.css' %}" rel="stylesheet" /> -->
    <link href="{% static 'css/task.css' %}" rel="stylesheet" />
    <link href="{% static 'css/CalendarPicker.style.css' %}" rel="stylesheet" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:700">

</head>

<body>
    <div class="wrapper">
        <div class="page_header">
            <a id="healthInfo_link" href="/createtasks/{{current}}/{{dates}}">FOOLERTON</a>
        </div>

        <div class="main_columns">
            <div class="sidebar">
                <div class="sidebar_wrapper">

                    <h3>Patient:</h3>
                    {% for ppl in people %}
                    <p id="patient_name"><a id="patient_link"
                            href="http://127.0.0.1:8000/createtasks/{{ ppl.pk }}/{{dates}}">{{ppl.name}}</a></p>
                    {%endfor%}
                    <div class="sidebar_line"></div>
                    <div class="sidebar_tabs">

                        <p class="sidebar_selected"><a id="tasks_link" class="sidebar_link"
                                href="http://127.0.0.1:8000/createtasks/{{current}}/{{dates}}">Tasks</a></p>
                        <p class="sidebar_item"><a id="healthInfo_link" class="sidebar_link"
                                href="http://127.0.0.1:8000/healthinfo/{{current}}">Health Information</a></p>
                    </div>
                </div>
            </div>
            <div class="main_content">
                <div class="topbar">
                    <a id="account_link" href="http://127.0.0.1:8000/docacc">
                        <img src="{% static 'assets/account_icon.svg' %}" id="account_icon" />
                        <span>{{name}}</span>
                    </a>
                </div>
                <div class="main_task_content">
                    <div class="task_today_col">
                        <div class="task_col_header">
                            <img src="{% static 'assets/task_icon.svg' %}" />
                            <span>Tasks for <span id="current-datestring"></span></span>
                        </div>
                        <div class="tasklist_container">
                            <ul class="tasklist">
                                {% for task in comments %}
                                <li>
                                    <button class="task_checkbox" id="checkbox_{{task.tasked.id}}"></button>
                                    <button class="tasklist_collapsible"
                                        id="task_{{task.tasked.id}}">{{task.tasked.details}}
                                        {{task.tasked.time}}</button>
                                    <div class="task_comments_container">
                                        {%for com in task.comment%}
                                        <div class="single_comment_container">
                                            <p class="comment_content">{{com.comment}}</p>
                                            <p class="comment_author">{{com.editBy}}</p>
                                            <p class="comment_datetime">{{com.editDate}} {{com.time}}</p>
                                        </div>
                                        {%endfor%}
                                    </div>
                                </li>

                                {%endfor%}
                            </ul>
                        </div>
                        <div class="task_action">
                            <select id="action_select" class="select_default">
                                <option value="0">View Tasks</option>
                                <option value="add_task">Add Task</option>
                                <option value="update_task">Update Task</option>
                                <option value="delete_task">Delete Task</option>
                                <option value="add_comment">Add Comment</option>
                            </select>
                            <button type="button" id="action_select_button">Next</button>
                        </div>
                    </div>

                    <!-- Only one of three will be shown at any one time, depending on the action selected -->
                    <!-- Calendar Block -->
                    <div id="calendar_col">
                        <div class="task_col_header">
                            <img src="{% static 'assets/calendar_icon.svg' %}" />
                            <span>Calendar</span>
                        </div>
                        <div id="calendar_container" class="{% static 'assets/arrow_left_icon.svg' %}">
                            <div class="calendar"></div>
                        </div>
                    </div>

                    <!-- Add Task Block -->
                    <div id="add_task_col" class="task_col">
                        <div class="task_col_header">
                            <img src="{% static 'assets/task_icon.svg' %}" />
                            <span id="task_create_status">Add Task</span>
                        </div>
                        <div class="add_task_container">
                            <form action="{% url 'foolerton:createdtasks' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="form_type" value="addtask">
                                <p class="field_label">Task Description:</p>
                                <input type="text" id="add_task_description_field" name="taskdesc" required>
                                <p class="field_label">Time of completion:</p>
                                <input type="time" id="add_task_time_field" name="timecomplete" required>
                                <p class="field_label">Date of Completion:</p>
                                <input type="date" id="add_task_date_field" name="datecomplete" required>
                                <p class="field_label">For:</p>
                                <select id="person_select" class="select_default" name="person">
                                    {% for ppl in people %}
                                    <option value={{ppl.pk}}>{{ppl.name}}</option>
                                    {%endfor%}
                                </select>
                                <input type="submit" id="add_task_button" class="task_button" value="Create">
                            </form>
                        </div>
                    </div>

                    <!-- Update Task Block -->
                    <div id="update_task_col" class="task_col">
                        <div class="task_col_header">
                            <img src="{% static 'assets/task_icon.svg' %}" />
                            <span id="task_update_status">Update Task</span>
                        </div>
                        <div class="update_task_container">
                            <form action="{% url 'foolerton:updatetasks' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="form_type" value="updatetask">
                                <input type="hidden" name="name" value="{{current}}">
                                <p class="field_label">Task Description:</p>
                                <input type="text" class="display_box" id="update_task_description_field"
                                    name="taskdesc" required>
                                <p class="field_label">Time of completion:</p>
                                <input type="time" class="display_box" id="update_task_time_field" name="timecomplete"
                                    required>
                                <p class="field_label">Date of Completion:</p>
                                <input type="date" class="display_box" id="update_task_date_field" name="datecomplete"
                                    required>
                                <p class="field_label">Task:</p>
                                <select id="person_select" class="select_default" name="task">
                                    {%for task in comments%}
                                    <option value="{{task.tasked.pk}}">{{task.tasked.details}} {{task.tasked.time}}
                                    </option>
                                    {%endfor%}
                                </select>
                                <input type="submit" id="update_task_button" class="task_button" value="Update">
                            </form>

                        </div>

                        <!-- <button type="button" id="add_comment_button" class="task_button">Create</button> -->

                    </div>

                    <!-- Delete Task Block -->
                    <div id="delete_task_col" class="task_col">
                        <div class="task_col_header">
                            <img src="{% static 'assets/task_icon.svg' %}" />
                            <span id="task_delete_status">Delete Task</span>
                        </div>
                        <div class="delete_task_container">
                            <p class="field_label">Task Selected</p>
                            <span class="selected_task_description display_box"></span>
                            <!-- <p class="field_label">Task Description:</p>
                            <p class = "display_box" id="task_description_field"></p>
                            <p class="field_label">Time of completion:</p>
                            <p class = "display_box" id="task_time_field"></p>
                            <p class="field_label">Date of Completion:</p>
                            <p class = "display_box" id="task_date_field"></p> -->
                        </div>

                        <button type="button" id="delete_task_button" class="task_button">Delete</button>

                    </div>


                    <!-- Add Comment Block -->
                    <div id="add_comment_col" class="task_col">
                        <div class="task_col_header">
                            <img src="{% static 'assets/task_icon.svg' %}" />
                            <span id="comment_create_status">Add Comment</span>
                        </div>
                        <div class="add_comment_container">
                            <form action="{% url 'foolerton:createcomments' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="name" value="{{current}}">
                                <input type="hidden" name="date" value="{{dates}}">
                                <p class="field_label">Task Selected</p>
                                <select id="action_select" class="select_default" name="task">
                                    {%for task in comments%}
                                    <option value="{{task.tasked.pk}}">{{task.tasked.details}} {{task.tasked.time}}
                                    </option>
                                    {%endfor%}
                                </select>
                                <p class="field_label">Comment Description:</p>
                                <textarea id="comment_description_field" name="comment_desc" cols="50" rows="10"
                                    required></textarea>
                                <input type="submit" id="add_comment_button" class="task_button" value="Create">
                            </form>
                        </div>

                        <!-- <button type="button" id="add_comment_button" class="task_button">Create</button> -->

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>


<script>
    var task_complete_status = "{{ task_completedFlag }}";
    var task_complete_status = JSON.parse(task_complete_status);
</script>

<!-- For the calendar -->
<script src="{% static 'scripts/CalendarPicker.js' %}"></script>
<!-- For misc stuff -->
<script src="{% static 'scripts/script.js' %}"></script>




</html>